# Generated by Django 3.2.7 on 2023-07-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=100)),
            ],
        ),
    ]
