# Generated by Django 3.2.7 on 2023-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workIt', models.CharField(max_length=40)),
                ('imgUrl', models.CharField(max_length=1000)),
                ('explore', models.CharField(max_length=100)),
            ],
        ),
    ]
