# Generated by Django 3.2.7 on 2023-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memories', models.CharField(max_length=1000)),
                ('galleryUrl', models.CharField(max_length=1000)),
            ],
        ),
    ]
