# Generated by Django 3.2.7 on 2023-07-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='memories',
        ),
    ]
