# Generated by Django 3.2.7 on 2023-07-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_gallery_memories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
