# Generated by Django 3.2.7 on 2023-07-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foryou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
