# Generated by Django 3.2.7 on 2023-07-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230711_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('foryou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foryou')),
            ],
        ),
    ]
