# Generated by Django 3.2.7 on 2023-07-11 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='foryou',
        ),
        migrations.DeleteModel(
            name='Foryou',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
