# Generated by Django 3.2.7 on 2023-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230711_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foryou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things', models.CharField(max_length=100)),
                ('thingdesc', models.CharField(max_length=1000)),
                ('thingimg', models.CharField(max_length=1000)),
            ],
        ),
    ]
