# Generated by Django 3.2.7 on 2023-07-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_foryou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Url',
        ),
    ]
