# Generated by Django 3.2.7 on 2023-07-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='foryou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foryou'),
        ),
    ]
